```{r}
library(tidyverse)
```

```{r}
matchsets <- read_csv("https://raw.githubusercontent.com/dwillis/NCAAWomensVolleyballData/main/data/ncaa_womens_volleyball_matchstats_2022.csv")
```

```{r}
teamquality <- matchsets |> 
  select(team, defensive_r_err, defensive_b_err, tb, hit_pct, total_attacks, team_score, opponent_score)
```

```{r}
teamtotals <- teamquality |> 
  group_by(team) |> 
  summarise(
    DefRErrAvg = mean(defensive_r_err), 
    DefBErrAvg = mean(defensive_b_err), 
    TBAvg = mean(tb),
    HitPctAvg = mean(hit_pct),
    TotalAttackAvg = mean(total_attacks),
    TeamScoreAvg = mean(team_score),
    OppScoreAvg = mean(opponent_score)
    ) 
```

```{r}
teamzscorevball <- teamtotals |>
  mutate(
    DefRErrZscore = as.numeric(scale(DefRErrAvg, center = TRUE, scale = TRUE)) * -1,
    DefBErrZscore = as.numeric(scale(DefBErrAvg, center = TRUE, scale = TRUE)) * -1,
    TBZscore = as.numeric(scale(TBAvg, center = TRUE, scale = TRUE)),
    HitPctZscore = as.numeric(scale(HitPctAvg, center = TRUE, scale = TRUE)),
    TotalAttackZscore = as.numeric(scale(TotalAttackAvg, center = TRUE, scale = TRUE)),
    TeamScoreZscore = as.numeric(scale(TeamScoreAvg, center = TRUE, scale = TRUE)),
    OppScoreZscore = as.numeric(scale(OppScoreAvg, center = TRUE, scale = TRUE)) * -1,
    TotalZscore = DefRErrZscore + DefBErrZscore + TBZscore + HitPctZscore + TotalAttackZscore + TeamScoreZscore + TeamScoreZscore + OppScoreZscore
    ) |> ungroup()
```

```{r}
head(teamzscorevball)
```

```{r}
teamzscorevball |> arrange(desc(TotalZscore))
```

Maryland is closer to a 0 z-score, which means that Maryland is much closer to the mean of the data score, with a slight over performance in team quality. 

```{r}
 marylandzscore <- teamzscorevball |> 
     group_by(team) |>
  filter(TotalZscore > 5) |>
  arrange(desc(TotalZscore))
```

I think a good story here would be the difference between Towson's success and Maryland's success within these merits. Towson is within the top 