According to https://themedalcount.com/2020/09/18/ranking-the-most-dominant-all-arounders-in-gymnastics-history/ , Simone Biles is the most decorated gymmnast of all time, and has the most AA (all-around) titles in women's gymnastics.

```{r}
library(tidyverse)
library(dplyr)
library(scales)
```

```{r}
gymnastics2021 <- read_csv("https://raw.githubusercontent.com/ucsas/gym2024data/main/cleandata/data_2017_2021.csv")
```
```{r}
gymnastics2022 <- read_csv("https://raw.githubusercontent.com/ucsas/gym2024data/main/cleandata/data_2022_2023.csv")
```
```{r}
teamavgs <- gymnastics2021 |> 
  group_by(Country, Apparatus) |> 
  summarise(
    ScoreAvg = mean(Score), 
    D_ScoreAvg = mean(D_Score), 
    E_ScoreAvg = mean(E_Score),
    PenaltyAvg = mean(Penalty)
    ) 
```
```{r}
teamavgs |>
  arrange(desc(ScoreAvg))
```


```{r}
womens_gymnastics |>
  group_by(Apparatus, Score) |>
  mutate(str_sub(Apparatus, start = 1L, end = -1L))
```


```{r}
ggplot() + 
  geom_point(data=womens_gymnastics, aes(x=`Score`, y=`D_Score`), color="grey")
```

